openapi: 3.0.4
info:
  title: Learn-Hub API
  description: Learn-Hub API's
  version: 0.1.9

servers:
  - url: http://localhost:5000/api/mainRoute
    description: Local server

paths:
  /signup:
    post:
      summary: Signup a new user
      description: Enter user details to register.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - password
                - phoneNumber
              properties:
                firstName:
                  type: string
                  example: Muzammil
                lastName:
                  type: string
                  example: Hussain
                email:
                  type: string
                  format: email
                  example: muzammilhussain63@gmail.com
                password:
                  type: string
                  example: SecureP@ssword2024!
                phoneNumber:
                  type: string
                  example: "8081985919"
      responses:
        "201":
          description: Signup successful
        "400":
          description: Validation failed
        "409":
          description: User already exists
        "500":
          description: Server error
  /login:
    post:
      summary: User login.
      description: Enter email and password to login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: muzammilhussain63@gmail.com
                password:
                  type: string
                  example: SecureP@ssword2024!
      responses:
        "200":
          description: Login successful
        "400":
          description: Invalid credentials
        "401":
          description: Credentials do not match
        "404":
          description: User not found
        "500":
          description: Internal server error

