import React, { useEffect, useState } from "react";
import { Accordion, Button, Row, Col, Card, Form } from "react-bootstrap";
import { getApi } from "../helper/helper.js";

const VectorDbDoc = () => {
    const [copiedCode, setCopiedCode] = useState(null);
    const [vectorDbData, setVectorDbData] = useState([]);
    const [searchTerm, setSearchTerm] = useState("");

    const handleCopy = async (code, key) => {
        try {
            await navigator.clipboard.writeText(code);
            setCopiedCode(key);
            setTimeout(() => setCopiedCode(null), 2000);
        } catch (err) {
            console.error("Copy failed:", err);
        }
    };

    useEffect(() => {
        const fetchTopics = async () => {
            try {
                const response = await getApi("vector-DB");
                console.log("------------------------>>>>>>>>>>>>>>>>>>>>>>>>", response?.data?.data?.sort((a, b) => a.id - b.id))
                setVectorDbData(
                    response?.data?.data?.sort((a, b) => a.id - b.id) || []
                );
            } catch (error) {
                setVectorDbData([]);
                console.error("Error fetching topics:", error);
            }
        };
        fetchTopics();
    }, []);

    // Filtered data based on search term
    const filteredData = vectorDbData.filter((section) => {
        const term = searchTerm.toLowerCase();
        return (
            section.title.toLowerCase().includes(term) ||
            section.list?.some((item) => item.toLowerCase().includes(term)) ||
            section.code?.some((codeBlock) =>
                codeBlock.content.toLowerCase().includes(term)
            )
        );
    });

    return (
        <div className="card border-0 shadow-lg bg-white">
            <div className="card-body px-4 px-md-5">
                <h2 className="text-primary fw-bold mb-4">
                    📚 Vector Database Documentation
                </h2>

                {/* 🔎 Search bar */}
                <Form className="mb-4">
                    <Form.Control
                        type="text"
                        placeholder="🔎 Search topics, code, or descriptions..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                    />
                </Form>

                <Row className="mb-4">
                    <Col md={6} className="mb-3">
                        <Card className="shadow-sm border-0 h-100">
                            <Card.Body>
                                <h5 className="fw-bold text-warning">📦 Installation</h5>
                                <p className="text-muted small">
                                    Install popular Vector Databases using npm or pip.
                                </p>
                                <pre className="bg-dark text-white small p-3 rounded mt-2 overflow-auto">
                  <code>npm install weaviate-client</code>
                </pre>
                                <pre className="bg-dark text-white small p-3 rounded mt-2 overflow-auto">
                  <code>npm install @pinecone-database/pinecone</code>
                </pre>
                                <pre className="bg-dark text-white small p-3 rounded mt-2 overflow-auto">
                  <code>pip install faiss-cpu</code>
                </pre>
                            </Card.Body>
                        </Card>
                    </Col>

                    <Col md={6} className="mb-3">
                        <Card className="shadow-sm border-0 h-100">
                            <Card.Body>
                                <h5 className="fw-bold text-primary">
                                    🔒 What is a Vector Database?
                                </h5>
                                <p className="text-muted small">
                                    A Vector Database is designed to store and query
                                    high-dimensional vectors, typically embeddings from AI/ML
                                    models.
                                </p>
                                <ul className="text-muted small ps-3">
                                    <li>✅ Stores embeddings generated by ML models</li>
                                    <li>
                                        ✅ Optimized for similarity search (cosine, Euclidean)
                                    </li>
                                    <li>
                                        ✅ Powers semantic search & recommendation engines
                                    </li>
                                    <li>
                                        ✅ Handles billions of vector entries efficiently
                                    </li>
                                </ul>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>

                {/* --- Accordion vectorDbData --- */}
                <Accordion defaultActiveKey="0">
                    {filteredData.length > 0 ? (
                        filteredData.map((section, idx) => (
                            <Accordion.Item eventKey={String(idx)} key={section.id}>
                                <Accordion.Header>{section.title}</Accordion.Header>
                                <Accordion.Body>
                                    {section.list && (
                                        <ul className="text-muted small ps-3">
                                            {section.list.map((point, i) => (
                                                <li
                                                    key={i}
                                                    dangerouslySetInnerHTML={{ __html: point }}
                                                />
                                            ))}
                                        </ul>
                                    )}

                                    {section.code && section.code.length > 0 && (
                                        <div className="mt-3">
                                            {section.code.map((codeBlock) => (
                                                <div
                                                    key={codeBlock.key}
                                                    className="position-relative mb-3"
                                                >
                                                    <Button
                                                        size="sm"
                                                        variant={
                                                            copiedCode === codeBlock.key
                                                                ? "success"
                                                                : "outline-secondary"
                                                        }
                                                        className="position-absolute top-0 end-0 m-2"
                                                        onClick={() =>
                                                            handleCopy(codeBlock.content, codeBlock.key)
                                                        }
                                                    >
                                                        {copiedCode === codeBlock.key
                                                            ? "✅ Copied"
                                                            : "📋 Copy"}
                                                    </Button>
                                                    <pre className="bg-dark text-white small p-3 rounded mt-2 overflow-auto">
                            <code>{codeBlock.content}</code>
                          </pre>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </Accordion.Body>
                            </Accordion.Item>
                        ))
                    ) : (
                        <p className="text-muted small text-center mt-3">
                            ❌ No matching results found.
                        </p>
                    )}
                </Accordion>
            </div>
        </div>
    );
};

export default VectorDbDoc;
